# Generated by Django 4.1 on 2022-08-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooker', '0002_alter_organisation_registered_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='registered_users',
            field=models.ManyToManyField(blank=True, to='RoomBooker.user'),
        ),
    ]
